import { create, fromBinary, toBinary } from "@bufbuild/protobuf";
import { Protobuf, Types } from "@meshtastic/core";
import { numberToHexUnpadded } from "@noble/curves/abstract/utils";

export type DarkMeshChatKind = "broadcast" | "direct";

export interface ParsedDmdbFile {
  favoriteOnly: boolean;
  version: string;
  contacts: Protobuf.Admin.SharedContact[];
  gpsOnly?: boolean;
  backboneOnly?: boolean;
}

export interface RelayCandidate {
  node: Protobuf.Mesh.NodeInfo;
  confidence: number;
}

export const DMDB_SEPARATOR = "\u2620";
export const DMDB_VERSION = "0.1";
export const DMDB_HEADER_PREFIX = "DARKMESH_NODEDB_FILE";
const DMDB_ARGS_TAG = "ARGS|";
const DMDB_ARG_FAVORITE_ONLY = "1";
const DMDB_ARG_GPS_ONLY = "GPS";
const DMDB_ARG_BACKBONE_ONLY = "BACKBONE";
const CONTACT_SHARE_HOST = "meshtastic.org";
const CONTACT_SHARE_PATH = "/v/";
const BASE64_URL_PREFIX = "https://meshtastic.org/v/#";
const PLUS_CODE_ALPHABET = "23456789CFGHJMPQRVWX";
const PAIR_RESOLUTIONS = [20, 1, 0.05, 0.0025, 0.000125];

export function getNodeDisplayName(
  node?: Pick<Protobuf.Mesh.NodeInfo, "num" | "user">,
  fallbackNum?: number,
): string {
  if (node?.user?.longName) {
    return node.user.longName;
  }
  const short = getNodeShortName(node);
  if (short) return short;
  const fallback = node?.num ?? fallbackNum;
  return fallback !== undefined
    ? numberToHexUnpadded(fallback).slice(-4).toUpperCase()
    : "Unknown node";
}

export function getNodeShortName(
  node?: Pick<Protobuf.Mesh.NodeInfo, "num" | "user">,
): string | undefined {
  const sn = node?.user?.shortName;
  if (sn && sn.trim().length > 0 && sn !== "UNK") return sn;
  // Prefer nameHex from user, then top-level node.nameHex, then derive from numeric node.num
  const nameHexFromUser = (node?.user as unknown as { nameHex?: string })?.nameHex;
  const nameHexTop = (node as unknown as { nameHex?: string })?.nameHex;
  const nameHex = nameHexFromUser ?? nameHexTop;
  if (nameHex && nameHex.length >= 4) return nameHex.slice(-4).toUpperCase();
  if (node?.num !== undefined) return numberToHexUnpadded(node.num).slice(-4).toUpperCase();
  return undefined;
}

export function getNodeLongName(
  node?: Pick<Protobuf.Mesh.NodeInfo, "num" | "user">,
): string | undefined {
  // Prefer explicit longName when available
  if (node?.user?.longName) return node.user.longName;

  // Fallback: show "Meshtastic <last4>" using nameHex when possible,
  // otherwise derive from numeric node id.
  const nameHexFromUser = (node?.user as unknown as { nameHex?: string })?.nameHex;
  const nameHexTop = (node as unknown as { nameHex?: string })?.nameHex;
  const nameHex = nameHexFromUser ?? nameHexTop;
  if (nameHex && nameHex.length > 0) return `Meshtastic ${nameHex.slice(-4).toLowerCase()}`;
  if (node?.num !== undefined)
    return `Meshtastic ${numberToHexUnpadded(node.num).slice(-4).toLowerCase()}`;
  return undefined;
}

export function resolveDestination(
  kind: DarkMeshChatKind,
  destination: number,
): {
  destination: Types.Destination;
  channel: Types.ChannelNumber;
} {
  return kind === "direct"
    ? {
        destination,
        channel: Types.ChannelNumber.Primary,
      }
    : {
        destination: "broadcast",
        channel: destination,
      };
}

function bytesToBase64Url(bytes: Uint8Array): string {
  const binary = Array.from(bytes, (byte) => String.fromCharCode(byte)).join("");
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}

function base64UrlToBytes(base64Url: string): Uint8Array {
  const padded = base64Url
    .replace(/-/g, "+")
    .replace(/_/g, "/")
    .padEnd(Math.ceil(base64Url.length / 4) * 4, "=");
  const binary = atob(padded);
  return Uint8Array.from(binary, (char) => char.charCodeAt(0));
}

export function buildSharedContactUrl(node: Protobuf.Mesh.NodeInfo): string {
  const sharedContact = create(Protobuf.Admin.SharedContactSchema, {
    nodeNum: node.num,
    user: node.user,
  });

  return `${BASE64_URL_PREFIX}${bytesToBase64Url(
    toBinary(Protobuf.Admin.SharedContactSchema, sharedContact),
  )}`;
}

export function parseSharedContactUrl(urlString: string): Protobuf.Admin.SharedContact {
  const url = new URL(urlString);

  if (
    !url.hash ||
    url.hostname.toLowerCase() !== CONTACT_SHARE_HOST ||
    url.pathname !== CONTACT_SHARE_PATH
  ) {
    throw new Error("Invalid Meshtastic shared contact URL");
  }

  return fromBinary(
    Protobuf.Admin.SharedContactSchema,
    base64UrlToBytes(url.hash.replace(/^#/, "")),
  );
}

export function buildDmdbContents(
  nodes: Protobuf.Mesh.NodeInfo[],
  myNodeNum: number,
  favoriteOnly = false,
  gpsOnly = false,
  backboneOnly = false,
): string {
  const args: string[] = [];
  if (favoriteOnly) args.push(DMDB_ARG_FAVORITE_ONLY);
  if (gpsOnly) args.push(DMDB_ARG_GPS_ONLY);
  if (backboneOnly) args.push(DMDB_ARG_BACKBONE_ONLY);

  const header = [
    `${DMDB_HEADER_PREFIX} v${DMDB_VERSION} GENERATED BY ${myNodeNum} at ${Date.now()}`,
    `${DMDB_ARGS_TAG}${args.join(",")}`,
  ].join(" ");

  const contacts = nodes
    .filter((node) => node.num !== myNodeNum)
    .filter((node) => !favoriteOnly || Boolean(node.isFavorite))
    // note: gpsOnly/backboneOnly are advisory flags encoded in the header; actual filtering
    // of node list can be done by callers prior to invoking this function if stricter
    // control is required. Keep export list consistent with favoriteOnly filter here.
    .sort((left, right) => (right.lastHeard ?? 0) - (left.lastHeard ?? 0))
    .map(buildSharedContactUrl);

  return `${header}${DMDB_SEPARATOR}${contacts.join(DMDB_SEPARATOR)}${DMDB_SEPARATOR}`;
}

export function parseDmdbContents(content: string): ParsedDmdbFile {
  const parts = content.split(DMDB_SEPARATOR).filter((part) => part.trim().length > 0);

  if (parts.length < 2) {
    throw new Error("Invalid or empty DarkMesh NodeDB export");
  }

  const [header, ...contactParts] = parts;
  const versionMatch = header?.match(/v([0-9.]+)/i);
  const version = versionMatch?.[1];

  if (!header || !header.startsWith(DMDB_HEADER_PREFIX) || !version) {
    throw new Error("Invalid DarkMesh NodeDB header");
  }

  const favoriteOnly = header.includes(`${DMDB_ARGS_TAG}${DMDB_ARG_FAVORITE_ONLY}`);
  const gpsOnly =
    header.includes(`${DMDB_ARGS_TAG}${DMDB_ARG_GPS_ONLY}`) || header.includes(DMDB_ARG_GPS_ONLY);
  const backboneOnly =
    header.includes(`${DMDB_ARGS_TAG}${DMDB_ARG_BACKBONE_ONLY}`) ||
    header.includes(DMDB_ARG_BACKBONE_ONLY);

  const contacts = contactParts.map(parseSharedContactUrl);

  return {
    favoriteOnly,
    gpsOnly,
    backboneOnly,
    version,
    contacts,
  };
}

function clipLatitude(latitude: number): number {
  return Math.max(-90, Math.min(90, latitude));
}

function normalizeLongitude(longitude: number): number {
  let normalized = longitude;
  while (normalized < -180) {
    normalized += 360;
  }
  while (normalized >= 180) {
    normalized -= 360;
  }
  return normalized;
}

export function encodePlusCode(latitude: number, longitude: number, codeLength = 8): string {
  if (!Number.isFinite(latitude) || !Number.isFinite(longitude)) {
    throw new Error("Invalid coordinates for Plus Code encoding");
  }

  if (codeLength < 2 || codeLength > 10 || codeLength % 2 !== 0) {
    throw new Error("Only even Plus Code lengths between 2 and 10 are supported");
  }

  const resolution =
    PAIR_RESOLUTIONS[Math.floor(codeLength / 2) - 1] ??
    PAIR_RESOLUTIONS[PAIR_RESOLUTIONS.length - 1] ??
    0.000125;
  let lat = clipLatitude(latitude);
  const lng = normalizeLongitude(longitude);

  if (lat === 90) {
    lat -= resolution / 2;
  }

  let adjustedLat = lat + 90;
  let adjustedLng = lng + 180;
  let code = "";

  for (let pairIndex = 0; pairIndex < codeLength / 2; pairIndex += 1) {
    const placeValue =
      PAIR_RESOLUTIONS[pairIndex] ?? PAIR_RESOLUTIONS[PAIR_RESOLUTIONS.length - 1] ?? 0.000125;
    const latDigit = Math.floor(adjustedLat / placeValue);
    const lngDigit = Math.floor(adjustedLng / placeValue);

    code += PLUS_CODE_ALPHABET[latDigit] ?? PLUS_CODE_ALPHABET[0];
    code += PLUS_CODE_ALPHABET[lngDigit] ?? PLUS_CODE_ALPHABET[0];

    adjustedLat -= latDigit * placeValue;
    adjustedLng -= lngDigit * placeValue;
  }

  return `${code.slice(0, 8)}+${code.slice(8)}`;
}

export function zuluTimeTag(date = new Date()): string {
  const hours = date.getUTCHours().toString().padStart(2, "0");
  const minutes = date.getUTCMinutes().toString().padStart(2, "0");
  return `Z${hours}${minutes}`;
}

export async function getCurrentLocation(): Promise<{
  latitude: number;
  longitude: number;
  altitude?: number;
}> {
  if (!("geolocation" in navigator)) {
    throw new Error("Geolocation is not available in this browser");
  }

  return await new Promise((resolve, reject) => {
    navigator.geolocation.getCurrentPosition(
      (position) => {
        resolve({
          latitude: position.coords.latitude,
          longitude: position.coords.longitude,
          altitude: position.coords.altitude ?? undefined,
        });
      },
      (error) => reject(error),
      {
        enableHighAccuracy: true,
        maximumAge: 30_000,
        timeout: 12_000,
      },
    );
  });
}

export async function buildDistressMessage(options: {
  prefix: string;
  text: string;
  includeName: boolean;
  includeGps: boolean;
  includeTime: boolean;
  myName?: string;
}): Promise<string> {
  const parts: string[] = [];

  if (options.prefix.trim()) {
    parts.push(options.prefix.trim());
  }

  if (options.includeGps) {
    try {
      const location = await getCurrentLocation();
      parts.push(encodePlusCode(location.latitude, location.longitude));

      if (typeof location.altitude === "number") {
        parts.push(`A${Math.round(location.altitude)}`);
      }
    } catch (error) {
      console.warn("[DarkMesh] Unable to encode live position for distress beacon", error);
    }
  }

  if (options.text.trim()) {
    parts.push(options.text.trim());
  }

  if (options.includeName && options.myName?.trim()) {
    parts.push(options.myName.trim());
  }

  if (options.includeTime) {
    parts.push(zuluTimeTag());
  }

  return parts.join(" ").trim() || "EMPTY Distress Beacon!";
}

export function normalizeHuntEndpoint(endpoint: string): string {
  return endpoint.trim().replace(/\/+$/g, "");
}

export function buildHuntPayload<T>(hunterId: string, packet: Types.PacketMetadata<T>): string {
  return JSON.stringify(
    {
      packet: {
        ...packet,
        rxTime: packet.rxTime instanceof Date ? packet.rxTime.toISOString() : packet.rxTime,
      },
      idHunter: hunterId,
    },
    null,
    2,
  );
}

export function normalizeHuntTraceroutePacket(
  packet: Types.PacketMetadata<Protobuf.Mesh.RouteDiscovery>,
  localNodeNum: number,
): Types.PacketMetadata<Protobuf.Mesh.RouteDiscovery> {
  if (!Number.isFinite(localNodeNum) || localNodeNum <= 0) {
    return packet;
  }

  return {
    ...packet,
    to: localNodeNum,
  };
}

export function resolveRelayCandidate(
  relayNodeId: number,
  nodes: Protobuf.Mesh.NodeInfo[],
  ourNodeNum?: number,
): RelayCandidate | undefined {
  const relayNodeSuffix = relayNodeId & 0xff;
  const candidates = nodes.filter(
    (node) =>
      node.num !== ourNodeNum && (node.lastHeard ?? 0) > 0 && (node.num & 0xff) === relayNodeSuffix,
  );

  if (candidates.length === 0) {
    return undefined;
  }

  const [firstCandidate, ...otherCandidates] = candidates;
  if (!firstCandidate) {
    return undefined;
  }

  const best = otherCandidates.reduce((currentBest, candidate) => {
    const bestHops = currentBest.hopsAway ?? Number.MAX_SAFE_INTEGER;
    const candidateHops = candidate.hopsAway ?? Number.MAX_SAFE_INTEGER;
    return candidateHops < bestHops ? candidate : currentBest;
  }, firstCandidate);

  const bestHop = best.hopsAway ?? 99;
  const averageHop =
    candidates.reduce((total, candidate) => total + (candidate.hopsAway ?? 99), 0) /
    candidates.length;
  const hopGap = averageHop - bestHop;

  let confidence = 50;
  confidence -= (candidates.length - 1) * 5;

  if (bestHop <= 1) {
    confidence += 25;
  } else if (bestHop === 2) {
    confidence += 15;
  } else if (bestHop <= 4) {
    confidence += 5;
  } else {
    confidence -= 10;
  }

  if (hopGap >= 3) {
    confidence += 20;
  } else if (hopGap >= 2) {
    confidence += 15;
  } else if (hopGap >= 1) {
    confidence += 10;
  }

  return {
    node: best,
    confidence: Math.max(0, Math.min(100, confidence)),
  };
}

export function toLocalDateTimeValue(date: Date): string {
  const shifted = new Date(date.getTime() - date.getTimezoneOffset() * 60_000);
  return shifted.toISOString().slice(0, 16);
}

export function computeNextRunAt(
  currentRunAt: number,
  recurrence: "once" | "daily" | "weekly",
): number | undefined {
  if (recurrence === "once") {
    return undefined;
  }

  const next = new Date(currentRunAt);
  const incrementDays = recurrence === "daily" ? 1 : 7;

  do {
    next.setDate(next.getDate() + incrementDays);
  } while (next.getTime() <= Date.now());

  return next.getTime();
}

export function distanceKm(
  from: { latitude: number; longitude: number },
  to: { latitude: number; longitude: number },
): number {
  const earthRadiusKm = 6371;
  const dLat = ((to.latitude - from.latitude) * Math.PI) / 180;
  const dLon = ((to.longitude - from.longitude) * Math.PI) / 180;
  const lat1 = (from.latitude * Math.PI) / 180;
  const lat2 = (to.latitude * Math.PI) / 180;

  const haversine =
    Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2;

  return 2 * earthRadiusKm * Math.asin(Math.sqrt(haversine));
}

export function createNodeInfoFromSharedContact(
  contact: Protobuf.Admin.SharedContact,
  favoriteOnly: boolean,
): Protobuf.Mesh.NodeInfo {
  return create(Protobuf.Mesh.NodeInfoSchema, {
    num: contact.nodeNum,
    user: contact.user,
    isFavorite: favoriteOnly,
  });
}
