import { create, toBinary, toJsonString } from "@bufbuild/protobuf";
import { describe, expect, it } from "vitest";
import {
  buildDmdbContents,
  getHuntBackgroundIntervalMs,
  getHuntTracerouteCandidates,
  buildHuntPayload,
  normalizeHuntTraceroutePacket,
  parseDmdbContents,
} from "./utils";
import { Protobuf, type Types } from "@meshtastic/core";

describe("DMDB export/import helpers", () => {
  it("encodes and parses ARGS flags and honors favorite-only filtering", () => {
    const myNodeNum = 1;

    const nodes: Array<any> = [
      {
        num: 2,
        isFavorite: true,
        position: { latitudeI: 123000000, longitudeI: 456000000 },
        user: { role: Protobuf.Config.Config_DeviceConfig_Role.ROUTER },
      },
      {
        num: 3,
        isFavorite: false,
        position: undefined,
        user: { role: Protobuf.Config.Config_DeviceConfig_Role.CLIENT },
      },
    ];

    const contents = buildDmdbContents(nodes, myNodeNum, true, true, true);
    const parsed = parseDmdbContents(contents);

    // favoriteOnly should be parsed
    expect(parsed.favoriteOnly).toBe(true);
    // gps/backbone flags should be present in header and parsed
    expect(parsed.gpsOnly).toBe(true);
    expect(parsed.backboneOnly).toBe(true);

    // Only the favorite node (num 2) should be exported when favoriteOnly = true
    expect(parsed.contacts.map((c) => c.nodeNum)).toEqual([2]);
  });

  it("parses files without ARGS gracefully", () => {
    const raw = "DARKMESH_NODEDB_FILE v0.1 GENERATED BY 1 at 0\u2620https://meshtastic.org/v/#";
    expect(() => parseDmdbContents(raw)).toThrow();
  });
});

describe("Hunt traceroute helpers", () => {
  it("maps hunt background modes to the Android scan intervals", () => {
    expect(getHuntBackgroundIntervalMs("fast")).toBe(31_000);
    expect(getHuntBackgroundIntervalMs("medium")).toBe(61_000);
    expect(getHuntBackgroundIntervalMs("slow")).toBe(121_000);
    expect(getHuntBackgroundIntervalMs("super_slow")).toBe(300_000);
    expect(getHuntBackgroundIntervalMs(undefined)).toBe(45_000);
  });

  it("orders hunt traceroute candidates by recency and excludes the local node", () => {
    const nodes = [
      { num: 0x1, lastHeard: 10 },
      { num: 0x2, lastHeard: 50 },
      { num: 0x3, lastHeard: 20 },
      { num: 0x4, lastHeard: 0 },
    ] satisfies Array<Pick<Protobuf.Mesh.NodeInfo, "num" | "lastHeard">>;

    expect(getHuntTracerouteCandidates(nodes, 0x2).map((node) => node.num)).toEqual([
      0x3, 0x1, 0x4,
    ]);
  });

  it("uses the connected local node as traceroute origin for hunt forwarding", () => {
    const localNodeNum = 0x12345678;
    const packet = {
      id: 7,
      rxTime: new Date("2026-04-30T12:00:00.000Z"),
      type: "broadcast",
      from: 0x9abcdef0,
      to: 0xffffff,
      channel: 0,
      data: {
        route: [0x11111111],
        routeBack: [],
        snrTowards: [12],
        snrBack: [],
      },
    } as Types.PacketMetadata<Protobuf.Mesh.RouteDiscovery>;

    const normalized = normalizeHuntTraceroutePacket(packet, localNodeNum);

    expect(normalized.to).toBe(localNodeNum);
    expect(normalized.from).toBe(packet.from);
    expect(packet.to).toBe(0xffffff);
  });

  it("serializes the normalized origin in hunt payloads", () => {
    const routeDiscovery = create(Protobuf.Mesh.RouteDiscoverySchema, {
      route: [0x11111111],
      routeBack: [],
      snrTowards: [12],
      snrBack: [],
    });
    const meshPacket = create(Protobuf.Mesh.MeshPacketSchema, {
      id: 7,
      rxTime: 1_777_550_400,
      from: 0x9abcdef0,
      to: 0xffffff,
      channel: 0,
      payloadVariant: {
        case: "decoded",
        value: create(Protobuf.Mesh.DataSchema, {
          portnum: Protobuf.Portnums.PortNum.TRACEROUTE_APP,
          payload: toBinary(Protobuf.Mesh.RouteDiscoverySchema, routeDiscovery),
        }),
      },
    });
    const packet = {
      id: 7,
      rxTime: new Date("2026-04-30T12:00:00.000Z"),
      type: "broadcast",
      from: 0x9abcdef0,
      to: 0xffffff,
      channel: 0,
      meshPacketJson: toJsonString(Protobuf.Mesh.MeshPacketSchema, meshPacket, {
        alwaysEmitImplicit: true,
        prettySpaces: 2,
      }),
      data: routeDiscovery,
    } as Types.PacketMetadata<Protobuf.Mesh.RouteDiscovery>;

    const payload = JSON.parse(
      buildHuntPayload("!12345678", normalizeHuntTraceroutePacket(packet, 0x12345678)),
    );

    expect(payload.idHunter).toBe("!12345678");
    expect(payload.packet.to).toBe(0xffffff);
    expect(payload.packet.decoded.portnum).toBe("TRACEROUTE_APP");
    expect(payload.packet.data).toBeUndefined();
  });
});
