import { describe, expect, it } from "vitest";
import { buildDmdbContents, parseDmdbContents } from "./utils";
import { Protobuf } from "@meshtastic/core";

describe("DMDB export/import helpers", () => {
  it("encodes and parses ARGS flags and honors favorite-only filtering", () => {
    const myNodeNum = 1;

    const nodes: Array<any> = [
      {
        num: 2,
        isFavorite: true,
        position: { latitudeI: 123000000, longitudeI: 456000000 },
        user: { role: Protobuf.Config.Config_DeviceConfig_Role.ROUTER },
      },
      {
        num: 3,
        isFavorite: false,
        position: undefined,
        user: { role: Protobuf.Config.Config_DeviceConfig_Role.CLIENT },
      },
    ];

    const contents = buildDmdbContents(nodes, myNodeNum, true, true, true);
    const parsed = parseDmdbContents(contents);

    // favoriteOnly should be parsed
    expect(parsed.favoriteOnly).toBe(true);
    // gps/backbone flags should be present in header and parsed
    expect(parsed.gpsOnly).toBe(true);
    expect(parsed.backboneOnly).toBe(true);

    // Only the favorite node (num 2) should be exported when favoriteOnly = true
    expect(parsed.contacts.map((c) => c.nodeNum)).toEqual([2]);
  });

  it("parses files without ARGS gracefully", () => {
    const raw = "DARKMESH_NODEDB_FILE v0.1 GENERATED BY 1 at 0\u2620https://meshtastic.org/v/#";
    expect(() => parseDmdbContents(raw)).toThrow();
  });
});
