import { describe, expect, it } from "vitest";
import {
  buildDmdbContents,
  buildHuntPayload,
  normalizeHuntTraceroutePacket,
  parseDmdbContents,
} from "./utils";
import { Protobuf, type Types } from "@meshtastic/core";

describe("DMDB export/import helpers", () => {
  it("encodes and parses ARGS flags and honors favorite-only filtering", () => {
    const myNodeNum = 1;

    const nodes: Array<any> = [
      {
        num: 2,
        isFavorite: true,
        position: { latitudeI: 123000000, longitudeI: 456000000 },
        user: { role: Protobuf.Config.Config_DeviceConfig_Role.ROUTER },
      },
      {
        num: 3,
        isFavorite: false,
        position: undefined,
        user: { role: Protobuf.Config.Config_DeviceConfig_Role.CLIENT },
      },
    ];

    const contents = buildDmdbContents(nodes, myNodeNum, true, true, true);
    const parsed = parseDmdbContents(contents);

    // favoriteOnly should be parsed
    expect(parsed.favoriteOnly).toBe(true);
    // gps/backbone flags should be present in header and parsed
    expect(parsed.gpsOnly).toBe(true);
    expect(parsed.backboneOnly).toBe(true);

    // Only the favorite node (num 2) should be exported when favoriteOnly = true
    expect(parsed.contacts.map((c) => c.nodeNum)).toEqual([2]);
  });

  it("parses files without ARGS gracefully", () => {
    const raw = "DARKMESH_NODEDB_FILE v0.1 GENERATED BY 1 at 0\u2620https://meshtastic.org/v/#";
    expect(() => parseDmdbContents(raw)).toThrow();
  });
});

describe("Hunt traceroute helpers", () => {
  it("uses the connected local node as traceroute origin for hunt forwarding", () => {
    const localNodeNum = 0x12345678;
    const packet = {
      id: 7,
      rxTime: new Date("2026-04-30T12:00:00.000Z"),
      type: "broadcast",
      from: 0x9abcdef0,
      to: 0xffffff,
      channel: 0,
      data: {
        route: [0x11111111],
        routeBack: [],
        snrTowards: [12],
        snrBack: [],
      },
    } as Types.PacketMetadata<Protobuf.Mesh.RouteDiscovery>;

    const normalized = normalizeHuntTraceroutePacket(packet, localNodeNum);

    expect(normalized.to).toBe(localNodeNum);
    expect(normalized.from).toBe(packet.from);
    expect(packet.to).toBe(0xffffff);
  });

  it("serializes the normalized origin in hunt payloads", () => {
    const packet = {
      id: 7,
      rxTime: new Date("2026-04-30T12:00:00.000Z"),
      type: "broadcast",
      from: 0x9abcdef0,
      to: 0xffffff,
      channel: 0,
      data: {
        route: [0x11111111],
        routeBack: [],
        snrTowards: [12],
        snrBack: [],
      },
    } as Types.PacketMetadata<Protobuf.Mesh.RouteDiscovery>;

    const payload = JSON.parse(
      buildHuntPayload("!12345678", normalizeHuntTraceroutePacket(packet, 0x12345678)),
    );

    expect(payload.idHunter).toBe("!12345678");
    expect(payload.packet.to).toBe(0x12345678);
  });
});
